---
- name: Deploy Bilal Store
  hosts: app
  become: true

  vars_files:
    - secrets.yml

  tasks:
    - name: Install Docker Python SDK
      apt:
        name: python3-docker
        state: present
        update_cache: true

    - name: Login to Amazon ECR
      shell: |
        aws ecr get-login-password --region ap-south-1 |
        docker login --username AWS --password-stdin 016617991046.dkr.ecr.ap-south-1.amazonaws.com
      changed_when: false

    - name: Pull Bilal Store image
      community.docker.docker_image:
        name: 016617991046.dkr.ecr.ap-south-1.amazonaws.com/bilal-store
        tag: latest
        source: pull

    - name: Create application directory
      file:
        path: /opt/bilal-store
        state: directory
        mode: "0755"

    - name: Create application environment file
      copy:
        dest: /opt/bilal-store/.env
        content: |
          DB_HOST={{ db_host }}
          DB_PORT={{ db_port }}
          DB_NAME={{ db_name }}
          DB_USER={{ db_user }}
          DB_PASS={{ db_password }}
          AWS_REGION={{ aws_region }}
          S3_BUCKET={{ s3_bucket }}
        owner: root
        group: root
        mode: "0600"

    - name: Run Bilal Store container
      community.docker.docker_container:
        name: bilal-store-app
        image: 016617991046.dkr.ecr.ap-south-1.amazonaws.com/bilal-store:latest
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "80:80"
        env_file: /opt/bilal-store/.env